// Code generated by ent, DO NOT EDIT.

package channelprovider

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the channelprovider type in the database.
	Label = "channel_provider"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldBaseURL holds the string denoting the base_url field in the database.
	FieldBaseURL = "base_url"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldRechargeAmount holds the string denoting the recharge_amount field in the database.
	FieldRechargeAmount = "recharge_amount"
	// FieldQuotaPerUnit holds the string denoting the quota_per_unit field in the database.
	FieldQuotaPerUnit = "quota_per_unit"
	// FieldBalance holds the string denoting the balance field in the database.
	FieldBalance = "balance"
	// FieldBalanceUnit holds the string denoting the balance_unit field in the database.
	FieldBalanceUnit = "balance_unit"
	// FieldBalanceCheckedAt holds the string denoting the balance_checked_at field in the database.
	FieldBalanceCheckedAt = "balance_checked_at"
	// FieldIsValid holds the string denoting the is_valid field in the database.
	FieldIsValid = "is_valid"
	// FieldSyncBalance holds the string denoting the sync_balance field in the database.
	FieldSyncBalance = "sync_balance"
	// FieldLastRefreshError holds the string denoting the last_refresh_error field in the database.
	FieldLastRefreshError = "last_refresh_error"
	// FieldGroupRatio holds the string denoting the group_ratio field in the database.
	FieldGroupRatio = "group_ratio"
	// FieldGroupRatioCheckedAt holds the string denoting the group_ratio_checked_at field in the database.
	FieldGroupRatioCheckedAt = "group_ratio_checked_at"
	// Table holds the table name of the channelprovider in the database.
	Table = "channel_providers"
)

// Columns holds all SQL columns for channelprovider fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldBaseURL,
	FieldDisplayName,
	FieldRechargeAmount,
	FieldQuotaPerUnit,
	FieldBalance,
	FieldBalanceUnit,
	FieldBalanceCheckedAt,
	FieldIsValid,
	FieldSyncBalance,
	FieldLastRefreshError,
	FieldGroupRatio,
	FieldGroupRatioCheckedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// BaseURLValidator is a validator for the "base_url" field. It is called by the builders before save.
	BaseURLValidator func(string) error
	// DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	DisplayNameValidator func(string) error
	// DefaultRechargeAmount holds the default value on creation for the "recharge_amount" field.
	DefaultRechargeAmount float64
	// DefaultQuotaPerUnit holds the default value on creation for the "quota_per_unit" field.
	DefaultQuotaPerUnit int64
	// DefaultBalanceUnit holds the default value on creation for the "balance_unit" field.
	DefaultBalanceUnit string
	// BalanceUnitValidator is a validator for the "balance_unit" field. It is called by the builders before save.
	BalanceUnitValidator func(string) error
	// DefaultIsValid holds the default value on creation for the "is_valid" field.
	DefaultIsValid bool
	// DefaultSyncBalance holds the default value on creation for the "sync_balance" field.
	DefaultSyncBalance bool
)

// OrderOption defines the ordering options for the ChannelProvider queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByBaseURL orders the results by the base_url field.
func ByBaseURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseURL, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByRechargeAmount orders the results by the recharge_amount field.
func ByRechargeAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRechargeAmount, opts...).ToFunc()
}

// ByQuotaPerUnit orders the results by the quota_per_unit field.
func ByQuotaPerUnit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaPerUnit, opts...).ToFunc()
}

// ByBalance orders the results by the balance field.
func ByBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalance, opts...).ToFunc()
}

// ByBalanceUnit orders the results by the balance_unit field.
func ByBalanceUnit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceUnit, opts...).ToFunc()
}

// ByBalanceCheckedAt orders the results by the balance_checked_at field.
func ByBalanceCheckedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceCheckedAt, opts...).ToFunc()
}

// ByIsValid orders the results by the is_valid field.
func ByIsValid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsValid, opts...).ToFunc()
}

// BySyncBalance orders the results by the sync_balance field.
func BySyncBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncBalance, opts...).ToFunc()
}

// ByLastRefreshError orders the results by the last_refresh_error field.
func ByLastRefreshError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastRefreshError, opts...).ToFunc()
}

// ByGroupRatioCheckedAt orders the results by the group_ratio_checked_at field.
func ByGroupRatioCheckedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupRatioCheckedAt, opts...).ToFunc()
}
