// Code generated by ent, DO NOT EDIT.

package channelprovider

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEQ(FieldUpdatedAt, v))
}

// BaseURL applies equality check predicate on the "base_url" field. It's identical to BaseURLEQ.
func BaseURL(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEQ(FieldBaseURL, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEQ(FieldDisplayName, v))
}

// RechargeAmount applies equality check predicate on the "recharge_amount" field. It's identical to RechargeAmountEQ.
func RechargeAmount(v float64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEQ(FieldRechargeAmount, v))
}

// QuotaPerUnit applies equality check predicate on the "quota_per_unit" field. It's identical to QuotaPerUnitEQ.
func QuotaPerUnit(v int64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEQ(FieldQuotaPerUnit, v))
}

// Balance applies equality check predicate on the "balance" field. It's identical to BalanceEQ.
func Balance(v float64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEQ(FieldBalance, v))
}

// BalanceUnit applies equality check predicate on the "balance_unit" field. It's identical to BalanceUnitEQ.
func BalanceUnit(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEQ(FieldBalanceUnit, v))
}

// BalanceCheckedAt applies equality check predicate on the "balance_checked_at" field. It's identical to BalanceCheckedAtEQ.
func BalanceCheckedAt(v time.Time) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEQ(FieldBalanceCheckedAt, v))
}

// IsValid applies equality check predicate on the "is_valid" field. It's identical to IsValidEQ.
func IsValid(v bool) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEQ(FieldIsValid, v))
}

// SyncBalance applies equality check predicate on the "sync_balance" field. It's identical to SyncBalanceEQ.
func SyncBalance(v bool) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEQ(FieldSyncBalance, v))
}

// LastRefreshError applies equality check predicate on the "last_refresh_error" field. It's identical to LastRefreshErrorEQ.
func LastRefreshError(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEQ(FieldLastRefreshError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldLTE(FieldUpdatedAt, v))
}

// BaseURLEQ applies the EQ predicate on the "base_url" field.
func BaseURLEQ(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEQ(FieldBaseURL, v))
}

// BaseURLNEQ applies the NEQ predicate on the "base_url" field.
func BaseURLNEQ(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldNEQ(FieldBaseURL, v))
}

// BaseURLIn applies the In predicate on the "base_url" field.
func BaseURLIn(vs ...string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldIn(FieldBaseURL, vs...))
}

// BaseURLNotIn applies the NotIn predicate on the "base_url" field.
func BaseURLNotIn(vs ...string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldNotIn(FieldBaseURL, vs...))
}

// BaseURLGT applies the GT predicate on the "base_url" field.
func BaseURLGT(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldGT(FieldBaseURL, v))
}

// BaseURLGTE applies the GTE predicate on the "base_url" field.
func BaseURLGTE(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldGTE(FieldBaseURL, v))
}

// BaseURLLT applies the LT predicate on the "base_url" field.
func BaseURLLT(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldLT(FieldBaseURL, v))
}

// BaseURLLTE applies the LTE predicate on the "base_url" field.
func BaseURLLTE(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldLTE(FieldBaseURL, v))
}

// BaseURLContains applies the Contains predicate on the "base_url" field.
func BaseURLContains(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldContains(FieldBaseURL, v))
}

// BaseURLHasPrefix applies the HasPrefix predicate on the "base_url" field.
func BaseURLHasPrefix(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldHasPrefix(FieldBaseURL, v))
}

// BaseURLHasSuffix applies the HasSuffix predicate on the "base_url" field.
func BaseURLHasSuffix(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldHasSuffix(FieldBaseURL, v))
}

// BaseURLEqualFold applies the EqualFold predicate on the "base_url" field.
func BaseURLEqualFold(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEqualFold(FieldBaseURL, v))
}

// BaseURLContainsFold applies the ContainsFold predicate on the "base_url" field.
func BaseURLContainsFold(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldContainsFold(FieldBaseURL, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameIsNil applies the IsNil predicate on the "display_name" field.
func DisplayNameIsNil() predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldIsNull(FieldDisplayName))
}

// DisplayNameNotNil applies the NotNil predicate on the "display_name" field.
func DisplayNameNotNil() predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldNotNull(FieldDisplayName))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldContainsFold(FieldDisplayName, v))
}

// RechargeAmountEQ applies the EQ predicate on the "recharge_amount" field.
func RechargeAmountEQ(v float64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEQ(FieldRechargeAmount, v))
}

// RechargeAmountNEQ applies the NEQ predicate on the "recharge_amount" field.
func RechargeAmountNEQ(v float64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldNEQ(FieldRechargeAmount, v))
}

// RechargeAmountIn applies the In predicate on the "recharge_amount" field.
func RechargeAmountIn(vs ...float64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldIn(FieldRechargeAmount, vs...))
}

// RechargeAmountNotIn applies the NotIn predicate on the "recharge_amount" field.
func RechargeAmountNotIn(vs ...float64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldNotIn(FieldRechargeAmount, vs...))
}

// RechargeAmountGT applies the GT predicate on the "recharge_amount" field.
func RechargeAmountGT(v float64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldGT(FieldRechargeAmount, v))
}

// RechargeAmountGTE applies the GTE predicate on the "recharge_amount" field.
func RechargeAmountGTE(v float64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldGTE(FieldRechargeAmount, v))
}

// RechargeAmountLT applies the LT predicate on the "recharge_amount" field.
func RechargeAmountLT(v float64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldLT(FieldRechargeAmount, v))
}

// RechargeAmountLTE applies the LTE predicate on the "recharge_amount" field.
func RechargeAmountLTE(v float64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldLTE(FieldRechargeAmount, v))
}

// QuotaPerUnitEQ applies the EQ predicate on the "quota_per_unit" field.
func QuotaPerUnitEQ(v int64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEQ(FieldQuotaPerUnit, v))
}

// QuotaPerUnitNEQ applies the NEQ predicate on the "quota_per_unit" field.
func QuotaPerUnitNEQ(v int64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldNEQ(FieldQuotaPerUnit, v))
}

// QuotaPerUnitIn applies the In predicate on the "quota_per_unit" field.
func QuotaPerUnitIn(vs ...int64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldIn(FieldQuotaPerUnit, vs...))
}

// QuotaPerUnitNotIn applies the NotIn predicate on the "quota_per_unit" field.
func QuotaPerUnitNotIn(vs ...int64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldNotIn(FieldQuotaPerUnit, vs...))
}

// QuotaPerUnitGT applies the GT predicate on the "quota_per_unit" field.
func QuotaPerUnitGT(v int64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldGT(FieldQuotaPerUnit, v))
}

// QuotaPerUnitGTE applies the GTE predicate on the "quota_per_unit" field.
func QuotaPerUnitGTE(v int64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldGTE(FieldQuotaPerUnit, v))
}

// QuotaPerUnitLT applies the LT predicate on the "quota_per_unit" field.
func QuotaPerUnitLT(v int64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldLT(FieldQuotaPerUnit, v))
}

// QuotaPerUnitLTE applies the LTE predicate on the "quota_per_unit" field.
func QuotaPerUnitLTE(v int64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldLTE(FieldQuotaPerUnit, v))
}

// BalanceEQ applies the EQ predicate on the "balance" field.
func BalanceEQ(v float64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEQ(FieldBalance, v))
}

// BalanceNEQ applies the NEQ predicate on the "balance" field.
func BalanceNEQ(v float64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldNEQ(FieldBalance, v))
}

// BalanceIn applies the In predicate on the "balance" field.
func BalanceIn(vs ...float64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldIn(FieldBalance, vs...))
}

// BalanceNotIn applies the NotIn predicate on the "balance" field.
func BalanceNotIn(vs ...float64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldNotIn(FieldBalance, vs...))
}

// BalanceGT applies the GT predicate on the "balance" field.
func BalanceGT(v float64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldGT(FieldBalance, v))
}

// BalanceGTE applies the GTE predicate on the "balance" field.
func BalanceGTE(v float64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldGTE(FieldBalance, v))
}

// BalanceLT applies the LT predicate on the "balance" field.
func BalanceLT(v float64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldLT(FieldBalance, v))
}

// BalanceLTE applies the LTE predicate on the "balance" field.
func BalanceLTE(v float64) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldLTE(FieldBalance, v))
}

// BalanceIsNil applies the IsNil predicate on the "balance" field.
func BalanceIsNil() predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldIsNull(FieldBalance))
}

// BalanceNotNil applies the NotNil predicate on the "balance" field.
func BalanceNotNil() predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldNotNull(FieldBalance))
}

// BalanceUnitEQ applies the EQ predicate on the "balance_unit" field.
func BalanceUnitEQ(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEQ(FieldBalanceUnit, v))
}

// BalanceUnitNEQ applies the NEQ predicate on the "balance_unit" field.
func BalanceUnitNEQ(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldNEQ(FieldBalanceUnit, v))
}

// BalanceUnitIn applies the In predicate on the "balance_unit" field.
func BalanceUnitIn(vs ...string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldIn(FieldBalanceUnit, vs...))
}

// BalanceUnitNotIn applies the NotIn predicate on the "balance_unit" field.
func BalanceUnitNotIn(vs ...string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldNotIn(FieldBalanceUnit, vs...))
}

// BalanceUnitGT applies the GT predicate on the "balance_unit" field.
func BalanceUnitGT(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldGT(FieldBalanceUnit, v))
}

// BalanceUnitGTE applies the GTE predicate on the "balance_unit" field.
func BalanceUnitGTE(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldGTE(FieldBalanceUnit, v))
}

// BalanceUnitLT applies the LT predicate on the "balance_unit" field.
func BalanceUnitLT(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldLT(FieldBalanceUnit, v))
}

// BalanceUnitLTE applies the LTE predicate on the "balance_unit" field.
func BalanceUnitLTE(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldLTE(FieldBalanceUnit, v))
}

// BalanceUnitContains applies the Contains predicate on the "balance_unit" field.
func BalanceUnitContains(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldContains(FieldBalanceUnit, v))
}

// BalanceUnitHasPrefix applies the HasPrefix predicate on the "balance_unit" field.
func BalanceUnitHasPrefix(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldHasPrefix(FieldBalanceUnit, v))
}

// BalanceUnitHasSuffix applies the HasSuffix predicate on the "balance_unit" field.
func BalanceUnitHasSuffix(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldHasSuffix(FieldBalanceUnit, v))
}

// BalanceUnitEqualFold applies the EqualFold predicate on the "balance_unit" field.
func BalanceUnitEqualFold(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEqualFold(FieldBalanceUnit, v))
}

// BalanceUnitContainsFold applies the ContainsFold predicate on the "balance_unit" field.
func BalanceUnitContainsFold(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldContainsFold(FieldBalanceUnit, v))
}

// BalanceCheckedAtEQ applies the EQ predicate on the "balance_checked_at" field.
func BalanceCheckedAtEQ(v time.Time) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEQ(FieldBalanceCheckedAt, v))
}

// BalanceCheckedAtNEQ applies the NEQ predicate on the "balance_checked_at" field.
func BalanceCheckedAtNEQ(v time.Time) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldNEQ(FieldBalanceCheckedAt, v))
}

// BalanceCheckedAtIn applies the In predicate on the "balance_checked_at" field.
func BalanceCheckedAtIn(vs ...time.Time) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldIn(FieldBalanceCheckedAt, vs...))
}

// BalanceCheckedAtNotIn applies the NotIn predicate on the "balance_checked_at" field.
func BalanceCheckedAtNotIn(vs ...time.Time) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldNotIn(FieldBalanceCheckedAt, vs...))
}

// BalanceCheckedAtGT applies the GT predicate on the "balance_checked_at" field.
func BalanceCheckedAtGT(v time.Time) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldGT(FieldBalanceCheckedAt, v))
}

// BalanceCheckedAtGTE applies the GTE predicate on the "balance_checked_at" field.
func BalanceCheckedAtGTE(v time.Time) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldGTE(FieldBalanceCheckedAt, v))
}

// BalanceCheckedAtLT applies the LT predicate on the "balance_checked_at" field.
func BalanceCheckedAtLT(v time.Time) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldLT(FieldBalanceCheckedAt, v))
}

// BalanceCheckedAtLTE applies the LTE predicate on the "balance_checked_at" field.
func BalanceCheckedAtLTE(v time.Time) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldLTE(FieldBalanceCheckedAt, v))
}

// BalanceCheckedAtIsNil applies the IsNil predicate on the "balance_checked_at" field.
func BalanceCheckedAtIsNil() predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldIsNull(FieldBalanceCheckedAt))
}

// BalanceCheckedAtNotNil applies the NotNil predicate on the "balance_checked_at" field.
func BalanceCheckedAtNotNil() predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldNotNull(FieldBalanceCheckedAt))
}

// IsValidEQ applies the EQ predicate on the "is_valid" field.
func IsValidEQ(v bool) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEQ(FieldIsValid, v))
}

// IsValidNEQ applies the NEQ predicate on the "is_valid" field.
func IsValidNEQ(v bool) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldNEQ(FieldIsValid, v))
}

// SyncBalanceEQ applies the EQ predicate on the "sync_balance" field.
func SyncBalanceEQ(v bool) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEQ(FieldSyncBalance, v))
}

// SyncBalanceNEQ applies the NEQ predicate on the "sync_balance" field.
func SyncBalanceNEQ(v bool) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldNEQ(FieldSyncBalance, v))
}

// LastRefreshErrorEQ applies the EQ predicate on the "last_refresh_error" field.
func LastRefreshErrorEQ(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEQ(FieldLastRefreshError, v))
}

// LastRefreshErrorNEQ applies the NEQ predicate on the "last_refresh_error" field.
func LastRefreshErrorNEQ(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldNEQ(FieldLastRefreshError, v))
}

// LastRefreshErrorIn applies the In predicate on the "last_refresh_error" field.
func LastRefreshErrorIn(vs ...string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldIn(FieldLastRefreshError, vs...))
}

// LastRefreshErrorNotIn applies the NotIn predicate on the "last_refresh_error" field.
func LastRefreshErrorNotIn(vs ...string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldNotIn(FieldLastRefreshError, vs...))
}

// LastRefreshErrorGT applies the GT predicate on the "last_refresh_error" field.
func LastRefreshErrorGT(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldGT(FieldLastRefreshError, v))
}

// LastRefreshErrorGTE applies the GTE predicate on the "last_refresh_error" field.
func LastRefreshErrorGTE(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldGTE(FieldLastRefreshError, v))
}

// LastRefreshErrorLT applies the LT predicate on the "last_refresh_error" field.
func LastRefreshErrorLT(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldLT(FieldLastRefreshError, v))
}

// LastRefreshErrorLTE applies the LTE predicate on the "last_refresh_error" field.
func LastRefreshErrorLTE(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldLTE(FieldLastRefreshError, v))
}

// LastRefreshErrorContains applies the Contains predicate on the "last_refresh_error" field.
func LastRefreshErrorContains(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldContains(FieldLastRefreshError, v))
}

// LastRefreshErrorHasPrefix applies the HasPrefix predicate on the "last_refresh_error" field.
func LastRefreshErrorHasPrefix(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldHasPrefix(FieldLastRefreshError, v))
}

// LastRefreshErrorHasSuffix applies the HasSuffix predicate on the "last_refresh_error" field.
func LastRefreshErrorHasSuffix(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldHasSuffix(FieldLastRefreshError, v))
}

// LastRefreshErrorIsNil applies the IsNil predicate on the "last_refresh_error" field.
func LastRefreshErrorIsNil() predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldIsNull(FieldLastRefreshError))
}

// LastRefreshErrorNotNil applies the NotNil predicate on the "last_refresh_error" field.
func LastRefreshErrorNotNil() predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldNotNull(FieldLastRefreshError))
}

// LastRefreshErrorEqualFold applies the EqualFold predicate on the "last_refresh_error" field.
func LastRefreshErrorEqualFold(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldEqualFold(FieldLastRefreshError, v))
}

// LastRefreshErrorContainsFold applies the ContainsFold predicate on the "last_refresh_error" field.
func LastRefreshErrorContainsFold(v string) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.FieldContainsFold(FieldLastRefreshError, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChannelProvider) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChannelProvider) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChannelProvider) predicate.ChannelProvider {
	return predicate.ChannelProvider(sql.NotPredicates(p))
}
