// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/channelprovider"
)

// ChannelProvider is the model entity for the ChannelProvider schema.
type ChannelProvider struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// BaseURL holds the value of the "base_url" field.
	BaseURL string `json:"base_url,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName *string `json:"display_name,omitempty"`
	// RechargeAmount holds the value of the "recharge_amount" field.
	RechargeAmount float64 `json:"recharge_amount,omitempty"`
	// QuotaPerUnit holds the value of the "quota_per_unit" field.
	QuotaPerUnit int64 `json:"quota_per_unit,omitempty"`
	// Balance holds the value of the "balance" field.
	Balance *float64 `json:"balance,omitempty"`
	// BalanceUnit holds the value of the "balance_unit" field.
	BalanceUnit string `json:"balance_unit,omitempty"`
	// BalanceCheckedAt holds the value of the "balance_checked_at" field.
	BalanceCheckedAt *time.Time `json:"balance_checked_at,omitempty"`
	// IsValid holds the value of the "is_valid" field.
	IsValid bool `json:"is_valid,omitempty"`
	// SyncBalance holds the value of the "sync_balance" field.
	SyncBalance bool `json:"sync_balance,omitempty"`
	// LastRefreshError holds the value of the "last_refresh_error" field.
	LastRefreshError *string `json:"last_refresh_error,omitempty"`
	// GroupRatio holds the value of the "group_ratio" field.
	GroupRatio map[string]float64 `json:"group_ratio,omitempty"`
	// GroupRatioCheckedAt holds the value of the "group_ratio_checked_at" field.
	GroupRatioCheckedAt *time.Time `json:"group_ratio_checked_at,omitempty"`
	selectValues        sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChannelProvider) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case channelprovider.FieldGroupRatio:
			values[i] = new([]byte)
		case channelprovider.FieldIsValid, channelprovider.FieldSyncBalance:
			values[i] = new(sql.NullBool)
		case channelprovider.FieldRechargeAmount, channelprovider.FieldBalance:
			values[i] = new(sql.NullFloat64)
		case channelprovider.FieldID, channelprovider.FieldQuotaPerUnit:
			values[i] = new(sql.NullInt64)
		case channelprovider.FieldBaseURL, channelprovider.FieldDisplayName, channelprovider.FieldBalanceUnit, channelprovider.FieldLastRefreshError:
			values[i] = new(sql.NullString)
		case channelprovider.FieldCreatedAt, channelprovider.FieldUpdatedAt, channelprovider.FieldBalanceCheckedAt, channelprovider.FieldGroupRatioCheckedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChannelProvider fields.
func (_m *ChannelProvider) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case channelprovider.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case channelprovider.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case channelprovider.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case channelprovider.FieldBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_url", values[i])
			} else if value.Valid {
				_m.BaseURL = value.String
			}
		case channelprovider.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = new(string)
				*_m.DisplayName = value.String
			}
		case channelprovider.FieldRechargeAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field recharge_amount", values[i])
			} else if value.Valid {
				_m.RechargeAmount = value.Float64
			}
		case channelprovider.FieldQuotaPerUnit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quota_per_unit", values[i])
			} else if value.Valid {
				_m.QuotaPerUnit = value.Int64
			}
		case channelprovider.FieldBalance:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance", values[i])
			} else if value.Valid {
				_m.Balance = new(float64)
				*_m.Balance = value.Float64
			}
		case channelprovider.FieldBalanceUnit:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field balance_unit", values[i])
			} else if value.Valid {
				_m.BalanceUnit = value.String
			}
		case channelprovider.FieldBalanceCheckedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field balance_checked_at", values[i])
			} else if value.Valid {
				_m.BalanceCheckedAt = new(time.Time)
				*_m.BalanceCheckedAt = value.Time
			}
		case channelprovider.FieldIsValid:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_valid", values[i])
			} else if value.Valid {
				_m.IsValid = value.Bool
			}
		case channelprovider.FieldSyncBalance:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field sync_balance", values[i])
			} else if value.Valid {
				_m.SyncBalance = value.Bool
			}
		case channelprovider.FieldLastRefreshError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_refresh_error", values[i])
			} else if value.Valid {
				_m.LastRefreshError = new(string)
				*_m.LastRefreshError = value.String
			}
		case channelprovider.FieldGroupRatio:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field group_ratio", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.GroupRatio); err != nil {
					return fmt.Errorf("unmarshal field group_ratio: %w", err)
				}
			}
		case channelprovider.FieldGroupRatioCheckedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field group_ratio_checked_at", values[i])
			} else if value.Valid {
				_m.GroupRatioCheckedAt = new(time.Time)
				*_m.GroupRatioCheckedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChannelProvider.
// This includes values selected through modifiers, order, etc.
func (_m *ChannelProvider) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ChannelProvider.
// Note that you need to call ChannelProvider.Unwrap() before calling this method if this ChannelProvider
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChannelProvider) Update() *ChannelProviderUpdateOne {
	return NewChannelProviderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChannelProvider entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChannelProvider) Unwrap() *ChannelProvider {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChannelProvider is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChannelProvider) String() string {
	var builder strings.Builder
	builder.WriteString("ChannelProvider(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("base_url=")
	builder.WriteString(_m.BaseURL)
	builder.WriteString(", ")
	if v := _m.DisplayName; v != nil {
		builder.WriteString("display_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("recharge_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.RechargeAmount))
	builder.WriteString(", ")
	builder.WriteString("quota_per_unit=")
	builder.WriteString(fmt.Sprintf("%v", _m.QuotaPerUnit))
	builder.WriteString(", ")
	if v := _m.Balance; v != nil {
		builder.WriteString("balance=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("balance_unit=")
	builder.WriteString(_m.BalanceUnit)
	builder.WriteString(", ")
	if v := _m.BalanceCheckedAt; v != nil {
		builder.WriteString("balance_checked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("is_valid=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsValid))
	builder.WriteString(", ")
	builder.WriteString("sync_balance=")
	builder.WriteString(fmt.Sprintf("%v", _m.SyncBalance))
	builder.WriteString(", ")
	if v := _m.LastRefreshError; v != nil {
		builder.WriteString("last_refresh_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("group_ratio=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupRatio))
	builder.WriteString(", ")
	if v := _m.GroupRatioCheckedAt; v != nil {
		builder.WriteString("group_ratio_checked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ChannelProviders is a parsable slice of ChannelProvider.
type ChannelProviders []*ChannelProvider
