// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/channelprovider"
)

// ChannelProviderCreate is the builder for creating a ChannelProvider entity.
type ChannelProviderCreate struct {
	config
	mutation *ChannelProviderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChannelProviderCreate) SetCreatedAt(v time.Time) *ChannelProviderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChannelProviderCreate) SetNillableCreatedAt(v *time.Time) *ChannelProviderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChannelProviderCreate) SetUpdatedAt(v time.Time) *ChannelProviderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChannelProviderCreate) SetNillableUpdatedAt(v *time.Time) *ChannelProviderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetBaseURL sets the "base_url" field.
func (_c *ChannelProviderCreate) SetBaseURL(v string) *ChannelProviderCreate {
	_c.mutation.SetBaseURL(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *ChannelProviderCreate) SetDisplayName(v string) *ChannelProviderCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_c *ChannelProviderCreate) SetNillableDisplayName(v *string) *ChannelProviderCreate {
	if v != nil {
		_c.SetDisplayName(*v)
	}
	return _c
}

// SetRechargeAmount sets the "recharge_amount" field.
func (_c *ChannelProviderCreate) SetRechargeAmount(v float64) *ChannelProviderCreate {
	_c.mutation.SetRechargeAmount(v)
	return _c
}

// SetNillableRechargeAmount sets the "recharge_amount" field if the given value is not nil.
func (_c *ChannelProviderCreate) SetNillableRechargeAmount(v *float64) *ChannelProviderCreate {
	if v != nil {
		_c.SetRechargeAmount(*v)
	}
	return _c
}

// SetQuotaPerUnit sets the "quota_per_unit" field.
func (_c *ChannelProviderCreate) SetQuotaPerUnit(v int64) *ChannelProviderCreate {
	_c.mutation.SetQuotaPerUnit(v)
	return _c
}

// SetNillableQuotaPerUnit sets the "quota_per_unit" field if the given value is not nil.
func (_c *ChannelProviderCreate) SetNillableQuotaPerUnit(v *int64) *ChannelProviderCreate {
	if v != nil {
		_c.SetQuotaPerUnit(*v)
	}
	return _c
}

// SetBalance sets the "balance" field.
func (_c *ChannelProviderCreate) SetBalance(v float64) *ChannelProviderCreate {
	_c.mutation.SetBalance(v)
	return _c
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_c *ChannelProviderCreate) SetNillableBalance(v *float64) *ChannelProviderCreate {
	if v != nil {
		_c.SetBalance(*v)
	}
	return _c
}

// SetBalanceUnit sets the "balance_unit" field.
func (_c *ChannelProviderCreate) SetBalanceUnit(v string) *ChannelProviderCreate {
	_c.mutation.SetBalanceUnit(v)
	return _c
}

// SetNillableBalanceUnit sets the "balance_unit" field if the given value is not nil.
func (_c *ChannelProviderCreate) SetNillableBalanceUnit(v *string) *ChannelProviderCreate {
	if v != nil {
		_c.SetBalanceUnit(*v)
	}
	return _c
}

// SetBalanceCheckedAt sets the "balance_checked_at" field.
func (_c *ChannelProviderCreate) SetBalanceCheckedAt(v time.Time) *ChannelProviderCreate {
	_c.mutation.SetBalanceCheckedAt(v)
	return _c
}

// SetNillableBalanceCheckedAt sets the "balance_checked_at" field if the given value is not nil.
func (_c *ChannelProviderCreate) SetNillableBalanceCheckedAt(v *time.Time) *ChannelProviderCreate {
	if v != nil {
		_c.SetBalanceCheckedAt(*v)
	}
	return _c
}

// SetIsValid sets the "is_valid" field.
func (_c *ChannelProviderCreate) SetIsValid(v bool) *ChannelProviderCreate {
	_c.mutation.SetIsValid(v)
	return _c
}

// SetNillableIsValid sets the "is_valid" field if the given value is not nil.
func (_c *ChannelProviderCreate) SetNillableIsValid(v *bool) *ChannelProviderCreate {
	if v != nil {
		_c.SetIsValid(*v)
	}
	return _c
}

// SetSyncBalance sets the "sync_balance" field.
func (_c *ChannelProviderCreate) SetSyncBalance(v bool) *ChannelProviderCreate {
	_c.mutation.SetSyncBalance(v)
	return _c
}

// SetNillableSyncBalance sets the "sync_balance" field if the given value is not nil.
func (_c *ChannelProviderCreate) SetNillableSyncBalance(v *bool) *ChannelProviderCreate {
	if v != nil {
		_c.SetSyncBalance(*v)
	}
	return _c
}

// SetLastRefreshError sets the "last_refresh_error" field.
func (_c *ChannelProviderCreate) SetLastRefreshError(v string) *ChannelProviderCreate {
	_c.mutation.SetLastRefreshError(v)
	return _c
}

// SetNillableLastRefreshError sets the "last_refresh_error" field if the given value is not nil.
func (_c *ChannelProviderCreate) SetNillableLastRefreshError(v *string) *ChannelProviderCreate {
	if v != nil {
		_c.SetLastRefreshError(*v)
	}
	return _c
}

// Mutation returns the ChannelProviderMutation object of the builder.
func (_c *ChannelProviderCreate) Mutation() *ChannelProviderMutation {
	return _c.mutation
}

// Save creates the ChannelProvider in the database.
func (_c *ChannelProviderCreate) Save(ctx context.Context) (*ChannelProvider, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChannelProviderCreate) SaveX(ctx context.Context) *ChannelProvider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelProviderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelProviderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChannelProviderCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := channelprovider.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := channelprovider.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.RechargeAmount(); !ok {
		v := channelprovider.DefaultRechargeAmount
		_c.mutation.SetRechargeAmount(v)
	}
	if _, ok := _c.mutation.QuotaPerUnit(); !ok {
		v := channelprovider.DefaultQuotaPerUnit
		_c.mutation.SetQuotaPerUnit(v)
	}
	if _, ok := _c.mutation.BalanceUnit(); !ok {
		v := channelprovider.DefaultBalanceUnit
		_c.mutation.SetBalanceUnit(v)
	}
	if _, ok := _c.mutation.IsValid(); !ok {
		v := channelprovider.DefaultIsValid
		_c.mutation.SetIsValid(v)
	}
	if _, ok := _c.mutation.SyncBalance(); !ok {
		v := channelprovider.DefaultSyncBalance
		_c.mutation.SetSyncBalance(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChannelProviderCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChannelProvider.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ChannelProvider.updated_at"`)}
	}
	if _, ok := _c.mutation.BaseURL(); !ok {
		return &ValidationError{Name: "base_url", err: errors.New(`ent: missing required field "ChannelProvider.base_url"`)}
	}
	if v, ok := _c.mutation.BaseURL(); ok {
		if err := channelprovider.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "ChannelProvider.base_url": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DisplayName(); ok {
		if err := channelprovider.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "ChannelProvider.display_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RechargeAmount(); !ok {
		return &ValidationError{Name: "recharge_amount", err: errors.New(`ent: missing required field "ChannelProvider.recharge_amount"`)}
	}
	if _, ok := _c.mutation.QuotaPerUnit(); !ok {
		return &ValidationError{Name: "quota_per_unit", err: errors.New(`ent: missing required field "ChannelProvider.quota_per_unit"`)}
	}
	if _, ok := _c.mutation.BalanceUnit(); !ok {
		return &ValidationError{Name: "balance_unit", err: errors.New(`ent: missing required field "ChannelProvider.balance_unit"`)}
	}
	if v, ok := _c.mutation.BalanceUnit(); ok {
		if err := channelprovider.BalanceUnitValidator(v); err != nil {
			return &ValidationError{Name: "balance_unit", err: fmt.Errorf(`ent: validator failed for field "ChannelProvider.balance_unit": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsValid(); !ok {
		return &ValidationError{Name: "is_valid", err: errors.New(`ent: missing required field "ChannelProvider.is_valid"`)}
	}
	if _, ok := _c.mutation.SyncBalance(); !ok {
		return &ValidationError{Name: "sync_balance", err: errors.New(`ent: missing required field "ChannelProvider.sync_balance"`)}
	}
	return nil
}

func (_c *ChannelProviderCreate) sqlSave(ctx context.Context) (*ChannelProvider, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChannelProviderCreate) createSpec() (*ChannelProvider, *sqlgraph.CreateSpec) {
	var (
		_node = &ChannelProvider{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(channelprovider.Table, sqlgraph.NewFieldSpec(channelprovider.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(channelprovider.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(channelprovider.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.BaseURL(); ok {
		_spec.SetField(channelprovider.FieldBaseURL, field.TypeString, value)
		_node.BaseURL = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(channelprovider.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = &value
	}
	if value, ok := _c.mutation.RechargeAmount(); ok {
		_spec.SetField(channelprovider.FieldRechargeAmount, field.TypeFloat64, value)
		_node.RechargeAmount = value
	}
	if value, ok := _c.mutation.QuotaPerUnit(); ok {
		_spec.SetField(channelprovider.FieldQuotaPerUnit, field.TypeInt64, value)
		_node.QuotaPerUnit = value
	}
	if value, ok := _c.mutation.Balance(); ok {
		_spec.SetField(channelprovider.FieldBalance, field.TypeFloat64, value)
		_node.Balance = &value
	}
	if value, ok := _c.mutation.BalanceUnit(); ok {
		_spec.SetField(channelprovider.FieldBalanceUnit, field.TypeString, value)
		_node.BalanceUnit = value
	}
	if value, ok := _c.mutation.BalanceCheckedAt(); ok {
		_spec.SetField(channelprovider.FieldBalanceCheckedAt, field.TypeTime, value)
		_node.BalanceCheckedAt = &value
	}
	if value, ok := _c.mutation.IsValid(); ok {
		_spec.SetField(channelprovider.FieldIsValid, field.TypeBool, value)
		_node.IsValid = value
	}
	if value, ok := _c.mutation.SyncBalance(); ok {
		_spec.SetField(channelprovider.FieldSyncBalance, field.TypeBool, value)
		_node.SyncBalance = value
	}
	if value, ok := _c.mutation.LastRefreshError(); ok {
		_spec.SetField(channelprovider.FieldLastRefreshError, field.TypeString, value)
		_node.LastRefreshError = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChannelProvider.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChannelProviderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ChannelProviderCreate) OnConflict(opts ...sql.ConflictOption) *ChannelProviderUpsertOne {
	_c.conflict = opts
	return &ChannelProviderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChannelProvider.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChannelProviderCreate) OnConflictColumns(columns ...string) *ChannelProviderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChannelProviderUpsertOne{
		create: _c,
	}
}

type (
	// ChannelProviderUpsertOne is the builder for "upsert"-ing
	//  one ChannelProvider node.
	ChannelProviderUpsertOne struct {
		create *ChannelProviderCreate
	}

	// ChannelProviderUpsert is the "OnConflict" setter.
	ChannelProviderUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelProviderUpsert) SetUpdatedAt(v time.Time) *ChannelProviderUpsert {
	u.Set(channelprovider.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelProviderUpsert) UpdateUpdatedAt() *ChannelProviderUpsert {
	u.SetExcluded(channelprovider.FieldUpdatedAt)
	return u
}

// SetBaseURL sets the "base_url" field.
func (u *ChannelProviderUpsert) SetBaseURL(v string) *ChannelProviderUpsert {
	u.Set(channelprovider.FieldBaseURL, v)
	return u
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *ChannelProviderUpsert) UpdateBaseURL() *ChannelProviderUpsert {
	u.SetExcluded(channelprovider.FieldBaseURL)
	return u
}

// SetDisplayName sets the "display_name" field.
func (u *ChannelProviderUpsert) SetDisplayName(v string) *ChannelProviderUpsert {
	u.Set(channelprovider.FieldDisplayName, v)
	return u
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *ChannelProviderUpsert) UpdateDisplayName() *ChannelProviderUpsert {
	u.SetExcluded(channelprovider.FieldDisplayName)
	return u
}

// ClearDisplayName clears the value of the "display_name" field.
func (u *ChannelProviderUpsert) ClearDisplayName() *ChannelProviderUpsert {
	u.SetNull(channelprovider.FieldDisplayName)
	return u
}

// SetRechargeAmount sets the "recharge_amount" field.
func (u *ChannelProviderUpsert) SetRechargeAmount(v float64) *ChannelProviderUpsert {
	u.Set(channelprovider.FieldRechargeAmount, v)
	return u
}

// UpdateRechargeAmount sets the "recharge_amount" field to the value that was provided on create.
func (u *ChannelProviderUpsert) UpdateRechargeAmount() *ChannelProviderUpsert {
	u.SetExcluded(channelprovider.FieldRechargeAmount)
	return u
}

// AddRechargeAmount adds v to the "recharge_amount" field.
func (u *ChannelProviderUpsert) AddRechargeAmount(v float64) *ChannelProviderUpsert {
	u.Add(channelprovider.FieldRechargeAmount, v)
	return u
}

// SetQuotaPerUnit sets the "quota_per_unit" field.
func (u *ChannelProviderUpsert) SetQuotaPerUnit(v int64) *ChannelProviderUpsert {
	u.Set(channelprovider.FieldQuotaPerUnit, v)
	return u
}

// UpdateQuotaPerUnit sets the "quota_per_unit" field to the value that was provided on create.
func (u *ChannelProviderUpsert) UpdateQuotaPerUnit() *ChannelProviderUpsert {
	u.SetExcluded(channelprovider.FieldQuotaPerUnit)
	return u
}

// AddQuotaPerUnit adds v to the "quota_per_unit" field.
func (u *ChannelProviderUpsert) AddQuotaPerUnit(v int64) *ChannelProviderUpsert {
	u.Add(channelprovider.FieldQuotaPerUnit, v)
	return u
}

// SetBalance sets the "balance" field.
func (u *ChannelProviderUpsert) SetBalance(v float64) *ChannelProviderUpsert {
	u.Set(channelprovider.FieldBalance, v)
	return u
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *ChannelProviderUpsert) UpdateBalance() *ChannelProviderUpsert {
	u.SetExcluded(channelprovider.FieldBalance)
	return u
}

// AddBalance adds v to the "balance" field.
func (u *ChannelProviderUpsert) AddBalance(v float64) *ChannelProviderUpsert {
	u.Add(channelprovider.FieldBalance, v)
	return u
}

// ClearBalance clears the value of the "balance" field.
func (u *ChannelProviderUpsert) ClearBalance() *ChannelProviderUpsert {
	u.SetNull(channelprovider.FieldBalance)
	return u
}

// SetBalanceUnit sets the "balance_unit" field.
func (u *ChannelProviderUpsert) SetBalanceUnit(v string) *ChannelProviderUpsert {
	u.Set(channelprovider.FieldBalanceUnit, v)
	return u
}

// UpdateBalanceUnit sets the "balance_unit" field to the value that was provided on create.
func (u *ChannelProviderUpsert) UpdateBalanceUnit() *ChannelProviderUpsert {
	u.SetExcluded(channelprovider.FieldBalanceUnit)
	return u
}

// SetBalanceCheckedAt sets the "balance_checked_at" field.
func (u *ChannelProviderUpsert) SetBalanceCheckedAt(v time.Time) *ChannelProviderUpsert {
	u.Set(channelprovider.FieldBalanceCheckedAt, v)
	return u
}

// UpdateBalanceCheckedAt sets the "balance_checked_at" field to the value that was provided on create.
func (u *ChannelProviderUpsert) UpdateBalanceCheckedAt() *ChannelProviderUpsert {
	u.SetExcluded(channelprovider.FieldBalanceCheckedAt)
	return u
}

// ClearBalanceCheckedAt clears the value of the "balance_checked_at" field.
func (u *ChannelProviderUpsert) ClearBalanceCheckedAt() *ChannelProviderUpsert {
	u.SetNull(channelprovider.FieldBalanceCheckedAt)
	return u
}

// SetIsValid sets the "is_valid" field.
func (u *ChannelProviderUpsert) SetIsValid(v bool) *ChannelProviderUpsert {
	u.Set(channelprovider.FieldIsValid, v)
	return u
}

// UpdateIsValid sets the "is_valid" field to the value that was provided on create.
func (u *ChannelProviderUpsert) UpdateIsValid() *ChannelProviderUpsert {
	u.SetExcluded(channelprovider.FieldIsValid)
	return u
}

// SetSyncBalance sets the "sync_balance" field.
func (u *ChannelProviderUpsert) SetSyncBalance(v bool) *ChannelProviderUpsert {
	u.Set(channelprovider.FieldSyncBalance, v)
	return u
}

// UpdateSyncBalance sets the "sync_balance" field to the value that was provided on create.
func (u *ChannelProviderUpsert) UpdateSyncBalance() *ChannelProviderUpsert {
	u.SetExcluded(channelprovider.FieldSyncBalance)
	return u
}

// SetLastRefreshError sets the "last_refresh_error" field.
func (u *ChannelProviderUpsert) SetLastRefreshError(v string) *ChannelProviderUpsert {
	u.Set(channelprovider.FieldLastRefreshError, v)
	return u
}

// UpdateLastRefreshError sets the "last_refresh_error" field to the value that was provided on create.
func (u *ChannelProviderUpsert) UpdateLastRefreshError() *ChannelProviderUpsert {
	u.SetExcluded(channelprovider.FieldLastRefreshError)
	return u
}

// ClearLastRefreshError clears the value of the "last_refresh_error" field.
func (u *ChannelProviderUpsert) ClearLastRefreshError() *ChannelProviderUpsert {
	u.SetNull(channelprovider.FieldLastRefreshError)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ChannelProvider.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChannelProviderUpsertOne) UpdateNewValues() *ChannelProviderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(channelprovider.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChannelProvider.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChannelProviderUpsertOne) Ignore() *ChannelProviderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChannelProviderUpsertOne) DoNothing() *ChannelProviderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChannelProviderCreate.OnConflict
// documentation for more info.
func (u *ChannelProviderUpsertOne) Update(set func(*ChannelProviderUpsert)) *ChannelProviderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChannelProviderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelProviderUpsertOne) SetUpdatedAt(v time.Time) *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelProviderUpsertOne) UpdateUpdatedAt() *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *ChannelProviderUpsertOne) SetBaseURL(v string) *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *ChannelProviderUpsertOne) UpdateBaseURL() *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.UpdateBaseURL()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *ChannelProviderUpsertOne) SetDisplayName(v string) *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *ChannelProviderUpsertOne) UpdateDisplayName() *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.UpdateDisplayName()
	})
}

// ClearDisplayName clears the value of the "display_name" field.
func (u *ChannelProviderUpsertOne) ClearDisplayName() *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.ClearDisplayName()
	})
}

// SetRechargeAmount sets the "recharge_amount" field.
func (u *ChannelProviderUpsertOne) SetRechargeAmount(v float64) *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.SetRechargeAmount(v)
	})
}

// AddRechargeAmount adds v to the "recharge_amount" field.
func (u *ChannelProviderUpsertOne) AddRechargeAmount(v float64) *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.AddRechargeAmount(v)
	})
}

// UpdateRechargeAmount sets the "recharge_amount" field to the value that was provided on create.
func (u *ChannelProviderUpsertOne) UpdateRechargeAmount() *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.UpdateRechargeAmount()
	})
}

// SetQuotaPerUnit sets the "quota_per_unit" field.
func (u *ChannelProviderUpsertOne) SetQuotaPerUnit(v int64) *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.SetQuotaPerUnit(v)
	})
}

// AddQuotaPerUnit adds v to the "quota_per_unit" field.
func (u *ChannelProviderUpsertOne) AddQuotaPerUnit(v int64) *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.AddQuotaPerUnit(v)
	})
}

// UpdateQuotaPerUnit sets the "quota_per_unit" field to the value that was provided on create.
func (u *ChannelProviderUpsertOne) UpdateQuotaPerUnit() *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.UpdateQuotaPerUnit()
	})
}

// SetBalance sets the "balance" field.
func (u *ChannelProviderUpsertOne) SetBalance(v float64) *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *ChannelProviderUpsertOne) AddBalance(v float64) *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *ChannelProviderUpsertOne) UpdateBalance() *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.UpdateBalance()
	})
}

// ClearBalance clears the value of the "balance" field.
func (u *ChannelProviderUpsertOne) ClearBalance() *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.ClearBalance()
	})
}

// SetBalanceUnit sets the "balance_unit" field.
func (u *ChannelProviderUpsertOne) SetBalanceUnit(v string) *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.SetBalanceUnit(v)
	})
}

// UpdateBalanceUnit sets the "balance_unit" field to the value that was provided on create.
func (u *ChannelProviderUpsertOne) UpdateBalanceUnit() *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.UpdateBalanceUnit()
	})
}

// SetBalanceCheckedAt sets the "balance_checked_at" field.
func (u *ChannelProviderUpsertOne) SetBalanceCheckedAt(v time.Time) *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.SetBalanceCheckedAt(v)
	})
}

// UpdateBalanceCheckedAt sets the "balance_checked_at" field to the value that was provided on create.
func (u *ChannelProviderUpsertOne) UpdateBalanceCheckedAt() *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.UpdateBalanceCheckedAt()
	})
}

// ClearBalanceCheckedAt clears the value of the "balance_checked_at" field.
func (u *ChannelProviderUpsertOne) ClearBalanceCheckedAt() *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.ClearBalanceCheckedAt()
	})
}

// SetIsValid sets the "is_valid" field.
func (u *ChannelProviderUpsertOne) SetIsValid(v bool) *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.SetIsValid(v)
	})
}

// UpdateIsValid sets the "is_valid" field to the value that was provided on create.
func (u *ChannelProviderUpsertOne) UpdateIsValid() *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.UpdateIsValid()
	})
}

// SetSyncBalance sets the "sync_balance" field.
func (u *ChannelProviderUpsertOne) SetSyncBalance(v bool) *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.SetSyncBalance(v)
	})
}

// UpdateSyncBalance sets the "sync_balance" field to the value that was provided on create.
func (u *ChannelProviderUpsertOne) UpdateSyncBalance() *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.UpdateSyncBalance()
	})
}

// SetLastRefreshError sets the "last_refresh_error" field.
func (u *ChannelProviderUpsertOne) SetLastRefreshError(v string) *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.SetLastRefreshError(v)
	})
}

// UpdateLastRefreshError sets the "last_refresh_error" field to the value that was provided on create.
func (u *ChannelProviderUpsertOne) UpdateLastRefreshError() *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.UpdateLastRefreshError()
	})
}

// ClearLastRefreshError clears the value of the "last_refresh_error" field.
func (u *ChannelProviderUpsertOne) ClearLastRefreshError() *ChannelProviderUpsertOne {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.ClearLastRefreshError()
	})
}

// Exec executes the query.
func (u *ChannelProviderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChannelProviderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChannelProviderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChannelProviderUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChannelProviderUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChannelProviderCreateBulk is the builder for creating many ChannelProvider entities in bulk.
type ChannelProviderCreateBulk struct {
	config
	err      error
	builders []*ChannelProviderCreate
	conflict []sql.ConflictOption
}

// Save creates the ChannelProvider entities in the database.
func (_c *ChannelProviderCreateBulk) Save(ctx context.Context) ([]*ChannelProvider, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChannelProvider, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChannelProviderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChannelProviderCreateBulk) SaveX(ctx context.Context) []*ChannelProvider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelProviderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelProviderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChannelProvider.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChannelProviderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ChannelProviderCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChannelProviderUpsertBulk {
	_c.conflict = opts
	return &ChannelProviderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChannelProvider.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChannelProviderCreateBulk) OnConflictColumns(columns ...string) *ChannelProviderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChannelProviderUpsertBulk{
		create: _c,
	}
}

// ChannelProviderUpsertBulk is the builder for "upsert"-ing
// a bulk of ChannelProvider nodes.
type ChannelProviderUpsertBulk struct {
	create *ChannelProviderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ChannelProvider.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChannelProviderUpsertBulk) UpdateNewValues() *ChannelProviderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(channelprovider.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChannelProvider.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChannelProviderUpsertBulk) Ignore() *ChannelProviderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChannelProviderUpsertBulk) DoNothing() *ChannelProviderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChannelProviderCreateBulk.OnConflict
// documentation for more info.
func (u *ChannelProviderUpsertBulk) Update(set func(*ChannelProviderUpsert)) *ChannelProviderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChannelProviderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelProviderUpsertBulk) SetUpdatedAt(v time.Time) *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelProviderUpsertBulk) UpdateUpdatedAt() *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *ChannelProviderUpsertBulk) SetBaseURL(v string) *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *ChannelProviderUpsertBulk) UpdateBaseURL() *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.UpdateBaseURL()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *ChannelProviderUpsertBulk) SetDisplayName(v string) *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *ChannelProviderUpsertBulk) UpdateDisplayName() *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.UpdateDisplayName()
	})
}

// ClearDisplayName clears the value of the "display_name" field.
func (u *ChannelProviderUpsertBulk) ClearDisplayName() *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.ClearDisplayName()
	})
}

// SetRechargeAmount sets the "recharge_amount" field.
func (u *ChannelProviderUpsertBulk) SetRechargeAmount(v float64) *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.SetRechargeAmount(v)
	})
}

// AddRechargeAmount adds v to the "recharge_amount" field.
func (u *ChannelProviderUpsertBulk) AddRechargeAmount(v float64) *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.AddRechargeAmount(v)
	})
}

// UpdateRechargeAmount sets the "recharge_amount" field to the value that was provided on create.
func (u *ChannelProviderUpsertBulk) UpdateRechargeAmount() *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.UpdateRechargeAmount()
	})
}

// SetQuotaPerUnit sets the "quota_per_unit" field.
func (u *ChannelProviderUpsertBulk) SetQuotaPerUnit(v int64) *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.SetQuotaPerUnit(v)
	})
}

// AddQuotaPerUnit adds v to the "quota_per_unit" field.
func (u *ChannelProviderUpsertBulk) AddQuotaPerUnit(v int64) *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.AddQuotaPerUnit(v)
	})
}

// UpdateQuotaPerUnit sets the "quota_per_unit" field to the value that was provided on create.
func (u *ChannelProviderUpsertBulk) UpdateQuotaPerUnit() *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.UpdateQuotaPerUnit()
	})
}

// SetBalance sets the "balance" field.
func (u *ChannelProviderUpsertBulk) SetBalance(v float64) *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *ChannelProviderUpsertBulk) AddBalance(v float64) *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *ChannelProviderUpsertBulk) UpdateBalance() *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.UpdateBalance()
	})
}

// ClearBalance clears the value of the "balance" field.
func (u *ChannelProviderUpsertBulk) ClearBalance() *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.ClearBalance()
	})
}

// SetBalanceUnit sets the "balance_unit" field.
func (u *ChannelProviderUpsertBulk) SetBalanceUnit(v string) *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.SetBalanceUnit(v)
	})
}

// UpdateBalanceUnit sets the "balance_unit" field to the value that was provided on create.
func (u *ChannelProviderUpsertBulk) UpdateBalanceUnit() *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.UpdateBalanceUnit()
	})
}

// SetBalanceCheckedAt sets the "balance_checked_at" field.
func (u *ChannelProviderUpsertBulk) SetBalanceCheckedAt(v time.Time) *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.SetBalanceCheckedAt(v)
	})
}

// UpdateBalanceCheckedAt sets the "balance_checked_at" field to the value that was provided on create.
func (u *ChannelProviderUpsertBulk) UpdateBalanceCheckedAt() *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.UpdateBalanceCheckedAt()
	})
}

// ClearBalanceCheckedAt clears the value of the "balance_checked_at" field.
func (u *ChannelProviderUpsertBulk) ClearBalanceCheckedAt() *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.ClearBalanceCheckedAt()
	})
}

// SetIsValid sets the "is_valid" field.
func (u *ChannelProviderUpsertBulk) SetIsValid(v bool) *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.SetIsValid(v)
	})
}

// UpdateIsValid sets the "is_valid" field to the value that was provided on create.
func (u *ChannelProviderUpsertBulk) UpdateIsValid() *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.UpdateIsValid()
	})
}

// SetSyncBalance sets the "sync_balance" field.
func (u *ChannelProviderUpsertBulk) SetSyncBalance(v bool) *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.SetSyncBalance(v)
	})
}

// UpdateSyncBalance sets the "sync_balance" field to the value that was provided on create.
func (u *ChannelProviderUpsertBulk) UpdateSyncBalance() *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.UpdateSyncBalance()
	})
}

// SetLastRefreshError sets the "last_refresh_error" field.
func (u *ChannelProviderUpsertBulk) SetLastRefreshError(v string) *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.SetLastRefreshError(v)
	})
}

// UpdateLastRefreshError sets the "last_refresh_error" field to the value that was provided on create.
func (u *ChannelProviderUpsertBulk) UpdateLastRefreshError() *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.UpdateLastRefreshError()
	})
}

// ClearLastRefreshError clears the value of the "last_refresh_error" field.
func (u *ChannelProviderUpsertBulk) ClearLastRefreshError() *ChannelProviderUpsertBulk {
	return u.Update(func(s *ChannelProviderUpsert) {
		s.ClearLastRefreshError()
	})
}

// Exec executes the query.
func (u *ChannelProviderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChannelProviderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChannelProviderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChannelProviderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
