// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/channelprovider"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ChannelProviderDelete is the builder for deleting a ChannelProvider entity.
type ChannelProviderDelete struct {
	config
	hooks    []Hook
	mutation *ChannelProviderMutation
}

// Where appends a list predicates to the ChannelProviderDelete builder.
func (_d *ChannelProviderDelete) Where(ps ...predicate.ChannelProvider) *ChannelProviderDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ChannelProviderDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChannelProviderDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ChannelProviderDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(channelprovider.Table, sqlgraph.NewFieldSpec(channelprovider.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ChannelProviderDeleteOne is the builder for deleting a single ChannelProvider entity.
type ChannelProviderDeleteOne struct {
	_d *ChannelProviderDelete
}

// Where appends a list predicates to the ChannelProviderDelete builder.
func (_d *ChannelProviderDeleteOne) Where(ps ...predicate.ChannelProvider) *ChannelProviderDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ChannelProviderDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{channelprovider.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChannelProviderDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
