// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/channelprovider"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ChannelProviderUpdate is the builder for updating ChannelProvider entities.
type ChannelProviderUpdate struct {
	config
	hooks    []Hook
	mutation *ChannelProviderMutation
}

// Where appends a list predicates to the ChannelProviderUpdate builder.
func (_u *ChannelProviderUpdate) Where(ps ...predicate.ChannelProvider) *ChannelProviderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChannelProviderUpdate) SetUpdatedAt(v time.Time) *ChannelProviderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *ChannelProviderUpdate) SetBaseURL(v string) *ChannelProviderUpdate {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *ChannelProviderUpdate) SetNillableBaseURL(v *string) *ChannelProviderUpdate {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ChannelProviderUpdate) SetDisplayName(v string) *ChannelProviderUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ChannelProviderUpdate) SetNillableDisplayName(v *string) *ChannelProviderUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// ClearDisplayName clears the value of the "display_name" field.
func (_u *ChannelProviderUpdate) ClearDisplayName() *ChannelProviderUpdate {
	_u.mutation.ClearDisplayName()
	return _u
}

// SetRechargeAmount sets the "recharge_amount" field.
func (_u *ChannelProviderUpdate) SetRechargeAmount(v float64) *ChannelProviderUpdate {
	_u.mutation.ResetRechargeAmount()
	_u.mutation.SetRechargeAmount(v)
	return _u
}

// SetNillableRechargeAmount sets the "recharge_amount" field if the given value is not nil.
func (_u *ChannelProviderUpdate) SetNillableRechargeAmount(v *float64) *ChannelProviderUpdate {
	if v != nil {
		_u.SetRechargeAmount(*v)
	}
	return _u
}

// AddRechargeAmount adds value to the "recharge_amount" field.
func (_u *ChannelProviderUpdate) AddRechargeAmount(v float64) *ChannelProviderUpdate {
	_u.mutation.AddRechargeAmount(v)
	return _u
}

// SetQuotaPerUnit sets the "quota_per_unit" field.
func (_u *ChannelProviderUpdate) SetQuotaPerUnit(v int64) *ChannelProviderUpdate {
	_u.mutation.ResetQuotaPerUnit()
	_u.mutation.SetQuotaPerUnit(v)
	return _u
}

// SetNillableQuotaPerUnit sets the "quota_per_unit" field if the given value is not nil.
func (_u *ChannelProviderUpdate) SetNillableQuotaPerUnit(v *int64) *ChannelProviderUpdate {
	if v != nil {
		_u.SetQuotaPerUnit(*v)
	}
	return _u
}

// AddQuotaPerUnit adds value to the "quota_per_unit" field.
func (_u *ChannelProviderUpdate) AddQuotaPerUnit(v int64) *ChannelProviderUpdate {
	_u.mutation.AddQuotaPerUnit(v)
	return _u
}

// SetBalance sets the "balance" field.
func (_u *ChannelProviderUpdate) SetBalance(v float64) *ChannelProviderUpdate {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *ChannelProviderUpdate) SetNillableBalance(v *float64) *ChannelProviderUpdate {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *ChannelProviderUpdate) AddBalance(v float64) *ChannelProviderUpdate {
	_u.mutation.AddBalance(v)
	return _u
}

// ClearBalance clears the value of the "balance" field.
func (_u *ChannelProviderUpdate) ClearBalance() *ChannelProviderUpdate {
	_u.mutation.ClearBalance()
	return _u
}

// SetBalanceUnit sets the "balance_unit" field.
func (_u *ChannelProviderUpdate) SetBalanceUnit(v string) *ChannelProviderUpdate {
	_u.mutation.SetBalanceUnit(v)
	return _u
}

// SetNillableBalanceUnit sets the "balance_unit" field if the given value is not nil.
func (_u *ChannelProviderUpdate) SetNillableBalanceUnit(v *string) *ChannelProviderUpdate {
	if v != nil {
		_u.SetBalanceUnit(*v)
	}
	return _u
}

// SetBalanceCheckedAt sets the "balance_checked_at" field.
func (_u *ChannelProviderUpdate) SetBalanceCheckedAt(v time.Time) *ChannelProviderUpdate {
	_u.mutation.SetBalanceCheckedAt(v)
	return _u
}

// SetNillableBalanceCheckedAt sets the "balance_checked_at" field if the given value is not nil.
func (_u *ChannelProviderUpdate) SetNillableBalanceCheckedAt(v *time.Time) *ChannelProviderUpdate {
	if v != nil {
		_u.SetBalanceCheckedAt(*v)
	}
	return _u
}

// ClearBalanceCheckedAt clears the value of the "balance_checked_at" field.
func (_u *ChannelProviderUpdate) ClearBalanceCheckedAt() *ChannelProviderUpdate {
	_u.mutation.ClearBalanceCheckedAt()
	return _u
}

// SetIsValid sets the "is_valid" field.
func (_u *ChannelProviderUpdate) SetIsValid(v bool) *ChannelProviderUpdate {
	_u.mutation.SetIsValid(v)
	return _u
}

// SetNillableIsValid sets the "is_valid" field if the given value is not nil.
func (_u *ChannelProviderUpdate) SetNillableIsValid(v *bool) *ChannelProviderUpdate {
	if v != nil {
		_u.SetIsValid(*v)
	}
	return _u
}

// SetSyncBalance sets the "sync_balance" field.
func (_u *ChannelProviderUpdate) SetSyncBalance(v bool) *ChannelProviderUpdate {
	_u.mutation.SetSyncBalance(v)
	return _u
}

// SetNillableSyncBalance sets the "sync_balance" field if the given value is not nil.
func (_u *ChannelProviderUpdate) SetNillableSyncBalance(v *bool) *ChannelProviderUpdate {
	if v != nil {
		_u.SetSyncBalance(*v)
	}
	return _u
}

// SetLastRefreshError sets the "last_refresh_error" field.
func (_u *ChannelProviderUpdate) SetLastRefreshError(v string) *ChannelProviderUpdate {
	_u.mutation.SetLastRefreshError(v)
	return _u
}

// SetNillableLastRefreshError sets the "last_refresh_error" field if the given value is not nil.
func (_u *ChannelProviderUpdate) SetNillableLastRefreshError(v *string) *ChannelProviderUpdate {
	if v != nil {
		_u.SetLastRefreshError(*v)
	}
	return _u
}

// ClearLastRefreshError clears the value of the "last_refresh_error" field.
func (_u *ChannelProviderUpdate) ClearLastRefreshError() *ChannelProviderUpdate {
	_u.mutation.ClearLastRefreshError()
	return _u
}

// SetGroupRatio sets the "group_ratio" field.
func (_u *ChannelProviderUpdate) SetGroupRatio(v map[string]float64) *ChannelProviderUpdate {
	_u.mutation.SetGroupRatio(v)
	return _u
}

// ClearGroupRatio clears the value of the "group_ratio" field.
func (_u *ChannelProviderUpdate) ClearGroupRatio() *ChannelProviderUpdate {
	_u.mutation.ClearGroupRatio()
	return _u
}

// SetGroupRatioCheckedAt sets the "group_ratio_checked_at" field.
func (_u *ChannelProviderUpdate) SetGroupRatioCheckedAt(v time.Time) *ChannelProviderUpdate {
	_u.mutation.SetGroupRatioCheckedAt(v)
	return _u
}

// SetNillableGroupRatioCheckedAt sets the "group_ratio_checked_at" field if the given value is not nil.
func (_u *ChannelProviderUpdate) SetNillableGroupRatioCheckedAt(v *time.Time) *ChannelProviderUpdate {
	if v != nil {
		_u.SetGroupRatioCheckedAt(*v)
	}
	return _u
}

// ClearGroupRatioCheckedAt clears the value of the "group_ratio_checked_at" field.
func (_u *ChannelProviderUpdate) ClearGroupRatioCheckedAt() *ChannelProviderUpdate {
	_u.mutation.ClearGroupRatioCheckedAt()
	return _u
}

// Mutation returns the ChannelProviderMutation object of the builder.
func (_u *ChannelProviderUpdate) Mutation() *ChannelProviderMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChannelProviderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelProviderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChannelProviderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelProviderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChannelProviderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := channelprovider.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelProviderUpdate) check() error {
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := channelprovider.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "ChannelProvider.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := channelprovider.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "ChannelProvider.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BalanceUnit(); ok {
		if err := channelprovider.BalanceUnitValidator(v); err != nil {
			return &ValidationError{Name: "balance_unit", err: fmt.Errorf(`ent: validator failed for field "ChannelProvider.balance_unit": %w`, err)}
		}
	}
	return nil
}

func (_u *ChannelProviderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelprovider.Table, channelprovider.Columns, sqlgraph.NewFieldSpec(channelprovider.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(channelprovider.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(channelprovider.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(channelprovider.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.DisplayNameCleared() {
		_spec.ClearField(channelprovider.FieldDisplayName, field.TypeString)
	}
	if value, ok := _u.mutation.RechargeAmount(); ok {
		_spec.SetField(channelprovider.FieldRechargeAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRechargeAmount(); ok {
		_spec.AddField(channelprovider.FieldRechargeAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.QuotaPerUnit(); ok {
		_spec.SetField(channelprovider.FieldQuotaPerUnit, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedQuotaPerUnit(); ok {
		_spec.AddField(channelprovider.FieldQuotaPerUnit, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(channelprovider.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(channelprovider.FieldBalance, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceCleared() {
		_spec.ClearField(channelprovider.FieldBalance, field.TypeFloat64)
	}
	if value, ok := _u.mutation.BalanceUnit(); ok {
		_spec.SetField(channelprovider.FieldBalanceUnit, field.TypeString, value)
	}
	if value, ok := _u.mutation.BalanceCheckedAt(); ok {
		_spec.SetField(channelprovider.FieldBalanceCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.BalanceCheckedAtCleared() {
		_spec.ClearField(channelprovider.FieldBalanceCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IsValid(); ok {
		_spec.SetField(channelprovider.FieldIsValid, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SyncBalance(); ok {
		_spec.SetField(channelprovider.FieldSyncBalance, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastRefreshError(); ok {
		_spec.SetField(channelprovider.FieldLastRefreshError, field.TypeString, value)
	}
	if _u.mutation.LastRefreshErrorCleared() {
		_spec.ClearField(channelprovider.FieldLastRefreshError, field.TypeString)
	}
	if value, ok := _u.mutation.GroupRatio(); ok {
		_spec.SetField(channelprovider.FieldGroupRatio, field.TypeJSON, value)
	}
	if _u.mutation.GroupRatioCleared() {
		_spec.ClearField(channelprovider.FieldGroupRatio, field.TypeJSON)
	}
	if value, ok := _u.mutation.GroupRatioCheckedAt(); ok {
		_spec.SetField(channelprovider.FieldGroupRatioCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.GroupRatioCheckedAtCleared() {
		_spec.ClearField(channelprovider.FieldGroupRatioCheckedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChannelProviderUpdateOne is the builder for updating a single ChannelProvider entity.
type ChannelProviderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChannelProviderMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChannelProviderUpdateOne) SetUpdatedAt(v time.Time) *ChannelProviderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *ChannelProviderUpdateOne) SetBaseURL(v string) *ChannelProviderUpdateOne {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *ChannelProviderUpdateOne) SetNillableBaseURL(v *string) *ChannelProviderUpdateOne {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ChannelProviderUpdateOne) SetDisplayName(v string) *ChannelProviderUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ChannelProviderUpdateOne) SetNillableDisplayName(v *string) *ChannelProviderUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// ClearDisplayName clears the value of the "display_name" field.
func (_u *ChannelProviderUpdateOne) ClearDisplayName() *ChannelProviderUpdateOne {
	_u.mutation.ClearDisplayName()
	return _u
}

// SetRechargeAmount sets the "recharge_amount" field.
func (_u *ChannelProviderUpdateOne) SetRechargeAmount(v float64) *ChannelProviderUpdateOne {
	_u.mutation.ResetRechargeAmount()
	_u.mutation.SetRechargeAmount(v)
	return _u
}

// SetNillableRechargeAmount sets the "recharge_amount" field if the given value is not nil.
func (_u *ChannelProviderUpdateOne) SetNillableRechargeAmount(v *float64) *ChannelProviderUpdateOne {
	if v != nil {
		_u.SetRechargeAmount(*v)
	}
	return _u
}

// AddRechargeAmount adds value to the "recharge_amount" field.
func (_u *ChannelProviderUpdateOne) AddRechargeAmount(v float64) *ChannelProviderUpdateOne {
	_u.mutation.AddRechargeAmount(v)
	return _u
}

// SetQuotaPerUnit sets the "quota_per_unit" field.
func (_u *ChannelProviderUpdateOne) SetQuotaPerUnit(v int64) *ChannelProviderUpdateOne {
	_u.mutation.ResetQuotaPerUnit()
	_u.mutation.SetQuotaPerUnit(v)
	return _u
}

// SetNillableQuotaPerUnit sets the "quota_per_unit" field if the given value is not nil.
func (_u *ChannelProviderUpdateOne) SetNillableQuotaPerUnit(v *int64) *ChannelProviderUpdateOne {
	if v != nil {
		_u.SetQuotaPerUnit(*v)
	}
	return _u
}

// AddQuotaPerUnit adds value to the "quota_per_unit" field.
func (_u *ChannelProviderUpdateOne) AddQuotaPerUnit(v int64) *ChannelProviderUpdateOne {
	_u.mutation.AddQuotaPerUnit(v)
	return _u
}

// SetBalance sets the "balance" field.
func (_u *ChannelProviderUpdateOne) SetBalance(v float64) *ChannelProviderUpdateOne {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *ChannelProviderUpdateOne) SetNillableBalance(v *float64) *ChannelProviderUpdateOne {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *ChannelProviderUpdateOne) AddBalance(v float64) *ChannelProviderUpdateOne {
	_u.mutation.AddBalance(v)
	return _u
}

// ClearBalance clears the value of the "balance" field.
func (_u *ChannelProviderUpdateOne) ClearBalance() *ChannelProviderUpdateOne {
	_u.mutation.ClearBalance()
	return _u
}

// SetBalanceUnit sets the "balance_unit" field.
func (_u *ChannelProviderUpdateOne) SetBalanceUnit(v string) *ChannelProviderUpdateOne {
	_u.mutation.SetBalanceUnit(v)
	return _u
}

// SetNillableBalanceUnit sets the "balance_unit" field if the given value is not nil.
func (_u *ChannelProviderUpdateOne) SetNillableBalanceUnit(v *string) *ChannelProviderUpdateOne {
	if v != nil {
		_u.SetBalanceUnit(*v)
	}
	return _u
}

// SetBalanceCheckedAt sets the "balance_checked_at" field.
func (_u *ChannelProviderUpdateOne) SetBalanceCheckedAt(v time.Time) *ChannelProviderUpdateOne {
	_u.mutation.SetBalanceCheckedAt(v)
	return _u
}

// SetNillableBalanceCheckedAt sets the "balance_checked_at" field if the given value is not nil.
func (_u *ChannelProviderUpdateOne) SetNillableBalanceCheckedAt(v *time.Time) *ChannelProviderUpdateOne {
	if v != nil {
		_u.SetBalanceCheckedAt(*v)
	}
	return _u
}

// ClearBalanceCheckedAt clears the value of the "balance_checked_at" field.
func (_u *ChannelProviderUpdateOne) ClearBalanceCheckedAt() *ChannelProviderUpdateOne {
	_u.mutation.ClearBalanceCheckedAt()
	return _u
}

// SetIsValid sets the "is_valid" field.
func (_u *ChannelProviderUpdateOne) SetIsValid(v bool) *ChannelProviderUpdateOne {
	_u.mutation.SetIsValid(v)
	return _u
}

// SetNillableIsValid sets the "is_valid" field if the given value is not nil.
func (_u *ChannelProviderUpdateOne) SetNillableIsValid(v *bool) *ChannelProviderUpdateOne {
	if v != nil {
		_u.SetIsValid(*v)
	}
	return _u
}

// SetSyncBalance sets the "sync_balance" field.
func (_u *ChannelProviderUpdateOne) SetSyncBalance(v bool) *ChannelProviderUpdateOne {
	_u.mutation.SetSyncBalance(v)
	return _u
}

// SetNillableSyncBalance sets the "sync_balance" field if the given value is not nil.
func (_u *ChannelProviderUpdateOne) SetNillableSyncBalance(v *bool) *ChannelProviderUpdateOne {
	if v != nil {
		_u.SetSyncBalance(*v)
	}
	return _u
}

// SetLastRefreshError sets the "last_refresh_error" field.
func (_u *ChannelProviderUpdateOne) SetLastRefreshError(v string) *ChannelProviderUpdateOne {
	_u.mutation.SetLastRefreshError(v)
	return _u
}

// SetNillableLastRefreshError sets the "last_refresh_error" field if the given value is not nil.
func (_u *ChannelProviderUpdateOne) SetNillableLastRefreshError(v *string) *ChannelProviderUpdateOne {
	if v != nil {
		_u.SetLastRefreshError(*v)
	}
	return _u
}

// ClearLastRefreshError clears the value of the "last_refresh_error" field.
func (_u *ChannelProviderUpdateOne) ClearLastRefreshError() *ChannelProviderUpdateOne {
	_u.mutation.ClearLastRefreshError()
	return _u
}

// SetGroupRatio sets the "group_ratio" field.
func (_u *ChannelProviderUpdateOne) SetGroupRatio(v map[string]float64) *ChannelProviderUpdateOne {
	_u.mutation.SetGroupRatio(v)
	return _u
}

// ClearGroupRatio clears the value of the "group_ratio" field.
func (_u *ChannelProviderUpdateOne) ClearGroupRatio() *ChannelProviderUpdateOne {
	_u.mutation.ClearGroupRatio()
	return _u
}

// SetGroupRatioCheckedAt sets the "group_ratio_checked_at" field.
func (_u *ChannelProviderUpdateOne) SetGroupRatioCheckedAt(v time.Time) *ChannelProviderUpdateOne {
	_u.mutation.SetGroupRatioCheckedAt(v)
	return _u
}

// SetNillableGroupRatioCheckedAt sets the "group_ratio_checked_at" field if the given value is not nil.
func (_u *ChannelProviderUpdateOne) SetNillableGroupRatioCheckedAt(v *time.Time) *ChannelProviderUpdateOne {
	if v != nil {
		_u.SetGroupRatioCheckedAt(*v)
	}
	return _u
}

// ClearGroupRatioCheckedAt clears the value of the "group_ratio_checked_at" field.
func (_u *ChannelProviderUpdateOne) ClearGroupRatioCheckedAt() *ChannelProviderUpdateOne {
	_u.mutation.ClearGroupRatioCheckedAt()
	return _u
}

// Mutation returns the ChannelProviderMutation object of the builder.
func (_u *ChannelProviderUpdateOne) Mutation() *ChannelProviderMutation {
	return _u.mutation
}

// Where appends a list predicates to the ChannelProviderUpdate builder.
func (_u *ChannelProviderUpdateOne) Where(ps ...predicate.ChannelProvider) *ChannelProviderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChannelProviderUpdateOne) Select(field string, fields ...string) *ChannelProviderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChannelProvider entity.
func (_u *ChannelProviderUpdateOne) Save(ctx context.Context) (*ChannelProvider, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelProviderUpdateOne) SaveX(ctx context.Context) *ChannelProvider {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChannelProviderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelProviderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChannelProviderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := channelprovider.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelProviderUpdateOne) check() error {
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := channelprovider.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "ChannelProvider.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := channelprovider.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "ChannelProvider.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BalanceUnit(); ok {
		if err := channelprovider.BalanceUnitValidator(v); err != nil {
			return &ValidationError{Name: "balance_unit", err: fmt.Errorf(`ent: validator failed for field "ChannelProvider.balance_unit": %w`, err)}
		}
	}
	return nil
}

func (_u *ChannelProviderUpdateOne) sqlSave(ctx context.Context) (_node *ChannelProvider, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelprovider.Table, channelprovider.Columns, sqlgraph.NewFieldSpec(channelprovider.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChannelProvider.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channelprovider.FieldID)
		for _, f := range fields {
			if !channelprovider.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != channelprovider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(channelprovider.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(channelprovider.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(channelprovider.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.DisplayNameCleared() {
		_spec.ClearField(channelprovider.FieldDisplayName, field.TypeString)
	}
	if value, ok := _u.mutation.RechargeAmount(); ok {
		_spec.SetField(channelprovider.FieldRechargeAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRechargeAmount(); ok {
		_spec.AddField(channelprovider.FieldRechargeAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.QuotaPerUnit(); ok {
		_spec.SetField(channelprovider.FieldQuotaPerUnit, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedQuotaPerUnit(); ok {
		_spec.AddField(channelprovider.FieldQuotaPerUnit, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(channelprovider.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(channelprovider.FieldBalance, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceCleared() {
		_spec.ClearField(channelprovider.FieldBalance, field.TypeFloat64)
	}
	if value, ok := _u.mutation.BalanceUnit(); ok {
		_spec.SetField(channelprovider.FieldBalanceUnit, field.TypeString, value)
	}
	if value, ok := _u.mutation.BalanceCheckedAt(); ok {
		_spec.SetField(channelprovider.FieldBalanceCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.BalanceCheckedAtCleared() {
		_spec.ClearField(channelprovider.FieldBalanceCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IsValid(); ok {
		_spec.SetField(channelprovider.FieldIsValid, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SyncBalance(); ok {
		_spec.SetField(channelprovider.FieldSyncBalance, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastRefreshError(); ok {
		_spec.SetField(channelprovider.FieldLastRefreshError, field.TypeString, value)
	}
	if _u.mutation.LastRefreshErrorCleared() {
		_spec.ClearField(channelprovider.FieldLastRefreshError, field.TypeString)
	}
	if value, ok := _u.mutation.GroupRatio(); ok {
		_spec.SetField(channelprovider.FieldGroupRatio, field.TypeJSON, value)
	}
	if _u.mutation.GroupRatioCleared() {
		_spec.ClearField(channelprovider.FieldGroupRatio, field.TypeJSON)
	}
	if value, ok := _u.mutation.GroupRatioCheckedAt(); ok {
		_spec.SetField(channelprovider.FieldGroupRatioCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.GroupRatioCheckedAtCleared() {
		_spec.ClearField(channelprovider.FieldGroupRatioCheckedAt, field.TypeTime)
	}
	_node = &ChannelProvider{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
